# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='player_skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='charactername',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingestion.Character'),
        ),
    ]
