# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_auto_20170510_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='charactername',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='ingestion.Character'),
        ),
    ]
