# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_auto_20170510_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='charactername',
            field=models.ForeignKey(db_column=b'character', default=b'', on_delete=django.db.models.deletion.CASCADE, to='ingestion.Character'),
        ),
    ]
