# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_auto_20170510_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='charactername',
            new_name='character',
        ),
    ]
