# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 05:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_auto_20170510_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[(b'Overall', b'Overall'), (b'Attack', b'Attack'), (b'Defence', b'Defence'), (b'Strength', b'Strength'), (b'Hitpoints', b'Hitpoints'), (b'Ranged', b'Ranged'), (b'Prayer', b'Prayer'), (b'Magic', b'Magic'), (b'Cooking', b'Cooking'), (b'Woodcutting', b'Woodcutting'), (b'Fletching', b'Fletching'), (b'Fishing', b'Fishing'), (b'Firemaking', b'Firemaking'), (b'Crafting', b'Crafting'), (b'Smithing', b'Smithing'), (b'Mining', b'Mining'), (b'Herblore', b'Herblore'), (b'Agility', b'Agility'), (b'Thieving', b'Thieving'), (b'Slayer', b'Slayer'), (b'Farming', b'Farming'), (b'Runecraft', b'Runecraft'), (b'Hunter', b'Hunter'), (b'Construction', b'Construction')], max_length=255),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
